
# Site settings
title: Technical Thoughts
name: Yasser Khan
subtitle: Random ramblings and rants about technical stuffs by Yasser Khan
email: yasser8@gmail.com
description: >
  A personal website about technical stuffs I find useful. Also, random ramblings and rants.
baseurl: ""
url: "https://yasu-khan.github.io/"
twitter_username: Yasu_khan
github_username:  yasu-khan
disqus_baseurl: "https://yasu-khan.github.io/"
disqus_shortname: yasu-khan
permalink: :title
cover: "/assets/header_image.jpg"
logo: "/assets/nr-logo.jpg"
ga_tracking_id: "UA-125975221-1"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yasser Khan"


# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks

#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name: Twitter
    icon: twitter
    username: Yasu_khan
    url: https://twitter.com/Yasu_khan
    desc: Follow me on Twitter
    share: true

  - name: Quora
    icon: quora
    username: YasserKhan
    url:
    desc: Follow me on Quora
    share: true

  - name: GitHub
    icon: github
    username: yasu-khan
    url: https://github.com/yasu-khan
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Yasser Khan
    url: https://www.linkedin.com/in/yasser-khan-219b9633/
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: true

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
#    fb_image: "/assets/nr-logo.jpg"
#    fb_image_width: 612
#    fb_image_height: 605
#    fb_image_type: "image/jpg"

    twitter_image: "/assets/nr-logo.jpg"

    os_repo: "https://github.com/yasu_khan/yasu-khan.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:yasu-khan.github.io.git"
